import Head from 'next/head'
import Header from '../componenets/Header'
import Nav from '../componenets/Nav'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <Header/>
       <Nav/>

    </div>
  )
}
